---
name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix profile install nixpkgs#alejandra nixpkgs#deadnix
      - uses: pre-commit/action@v3.0.1

  nix-build:
    name: Nix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: make check/nix

  bats:
    name: Bats tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix shell nixpkgs#bats --command make check/bats
